ERROR - 2025-08-31 09:16:53 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2025-08-31 09:54:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user '123'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '123', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2025-08-31 09:56:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2025-08-31 09:57:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
ERROR - 2025-08-31 09:57:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#5 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CI4\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI4\system\Database\Database.php(72): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI4\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CI4\system\Commands\Database\CreateDatabase.php(136): CodeIgniter\Database\Config::forge()
#4 C:\xampp\htdocs\CI4\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#5 C:\xampp\htdocs\CI4\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:create', Array)
#6 C:\xampp\htdocs\CI4\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\CI4\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\CI4\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-08-31 10:10:04 --> ErrorException: Undefined variable $title
[Method: GET, Route: halo]
in APPPATH\Views\halo_view.php on line 6.
 1 APPPATH\Views\halo_view.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $title', 'C:\\xampp\\htdocs\\CI4\\app\\Views\\halo_view.php', 6)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\CI4\\app\\Views\\halo_view.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('halo_view', [], true)
 5 APPPATH\Controllers\Halo.php(9): view('halo_view')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Halo->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Halo))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\CI4\\public\\index.php')
